### ISSUE TITLE
Give verifySession a flag that allows the API to be called even if there is no user

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-node#103]
- In this case, `req.session` will be `undefined`.
- Something like `verifySession(true)`

TODO:
- [x] Implementaion
- [x] Issue: If headers are set for unauthorised call, then we need to make sure those are sent to the frontend as well (or that those are handled - @bhumilsarvaiya )
- [x] Test
- [x] Docs

**Comment by bhumilsarvaiya** [comment]
Currently, verifySession accepts a boolean parameter `antiCsrfCheck` which is optional. i.e.

```ts
type requestHandler = (request: SessionRequest, response: Response, next: NextFunction) => Promise<void>;
verifySession(antiCsrfCheck?: boolean) => requestHandler;
```

If we add another optional parameter that allows the API to be called even if there is no session, let's call it `sessionRequired`. So the signature will become:

```ts
type requestHandler = (request: SessionRequest, response: Response, next: NextFunction) => Promise<void>;
verifySession(antiCsrfCheck?: boolean, sessionRequired?: boolean) => requestHandler;
```

Default value of `sessionRequired` will be `true`.

One drawback will be, for developers who just want to pass this a boolean that allows the API to be called even if there is no session, now also have to pass either `undefined` or `boolean` for `antiCsrfCheck` compulsorily. One way to counter this is to accept an object where user can pass possible flags. The verifySession function signature will then become like:

```ts
type verifySessionOptions?: {
    antiCsrfCheck?: boolean,
    sessionRequired?: boolean
};
type requestHandler = (request: SessionRequest, response: Response, next: NextFunction) => Promise<void>;
verifySession(options?: verifySessionOptions | boolean) => requestHandler;
```

Here, `options?: verifySessionOptions | boolean` is to make the changes backward compatible. In the documentation of the new `verifySession` function, we should only mention about `verifySessionOptions`.

**Comment by rishabhpoddar** [comment]
I prefer the method in which the user has to provide that object with the two keys.

**Comment by rishabhpoddar** [comment]
If `sessionRequired` is `false`, and no session is provided, I assume `req.session` will be `undefined`?

**Comment by bhumilsarvaiya** [comment]
Yes, that's correct

**Comment by rishabhpoddar** [comment]
@bhumilsarvaiya how would this interface be affected when we add anonymous sessions? We would ideally not want to do a breaking change by renaming this `sessionRequired` variable...

**Comment by bhumilsarvaiya** [comment]
@rishabhpoddar this depends on what the flow is that we intend to have for the anonymous session. Let's say we have a boolean later on for anonymous session in the `verifySession` function, `allowAnonymous`. We decide to create an anonymous session during `verifySession` function if any session is not there and `allowAnonymous` is set to `true`. One logic can be:
- if `allowAnonymous` is set to `false` and `sessionRequired` is set to `false`, we don't create anonymous session 
- if `allowAnonymous` is set to `true` and `sessionRequired` is set to `false`, we still don't create anonymous session as any session is optional for the API route. This simply means that `verifySession` function will yield a session which is either a normal session or an anonymous session or it will result in no session and all these are acceptable states.
- if `allowAnonymous` is set to `true` and `sessionRequired` is set to `true`, it can simply mean that the API route do require a session, if no session found, create an anonymous session.

But instead of using `sessionRequired`, we can change it to `allowOnlyAuthenticated`. And it deals only with normal session and not anonymous session. If the user wants an `OR` condition, i.e. `verifySession` should allow for either a normal session or an anonymous session, they should set both `allowOnlyAuthenticated` and `allowAnonymous` to `true`.

**Comment by rishabhpoddar** [comment]
Let's just go with `sessionRequired` for now.
