### ISSUE TITLE
Types are wrong in version 6.0.0

### ISSUE THREAD

**Issue by gusfune** [supertokens/supertokens-node#137]
It seems for some reason the type declarations in 6.0.0 are wrong or mismatched with the react/website package.
I noticed in my back-end config in nextJS the following error:
![Screen Shot 2021-06-18 at 10 03 18](https://user-images.githubusercontent.com/1147240/122528889-19c67e80-d01d-11eb-8d6f-2ab95c857ebf.png)

When looking at the type declarations I've found:
![Screen Shot 2021-06-18 at 10 03 31](https://user-images.githubusercontent.com/1147240/122528970-306cd580-d01d-11eb-924a-7c9f068108f8.png)

But when looking directly at `TypeInputSignUp`, I have this:
![Screen Shot 2021-06-18 at 10 03 56](https://user-images.githubusercontent.com/1147240/122529110-65792800-d01d-11eb-916a-a6ce93a5e969.png)

In 5.1.0, the `TypeInputSignUp` is actually:
![Screen Shot 2021-06-18 at 10 07 26](https://user-images.githubusercontent.com/1147240/122529154-71fd8080-d01d-11eb-9618-8a9b50fa2515.png)

Current fix: rollback to 5.1.0.

**Comment by rishabhpoddar** [comment]
hey @gusfune,
The type of `TypeInputSignUp` in 5.1.0 is [here](https://github.com/supertokens/supertokens-node/blob/5.1/lib/ts/recipe/thirdpartyemailpassword/types.ts#L107).

In the new release, we have removed `disableDefaultImplementation` and `handlePostSignUp` params from `TypeInputSignUp`.

For `handlePostSignUp`, you should now use the `override` feature:
```js
// backend
SuperTokens.init({
    appInfo: {...},
    supertokens: {...},
    recipeList: [
        ThirdPartyEmailPassword.init({
            override: {
                apis: (originalImplementation) => {
                    return {
                        ...originalImplementation,
                        signInUpPOST: async (input) => {
                            let response = await originalImplementation.signInUpPOST(input);
                            if (response.status === "OK") {
                                let { id, email } = response.user;
                                if (response.createdNewUser) {
                                    // TODO: post sign up logic
                                } else {
                                    // TODO: post sign in logic
                                }
                            }
                            return response;
                        }
                    }
                }
            }
        }),
    ]
});
```

------------------
Apologies for the breaking change across these versions, but we have been wanting to clean up the post callback functions since a long time - and this `override` feature is a good way of doing it.

**Comment by gusfune** [comment]
Ah ok, it wasn't clear that the override was going to dismantle the functions. No worries, I will close this as it's not a bug, rather a feature. Thanks for clearing it out! :)
