### ISSUE TITLE
How can I fix supertokens-core and supertokens-node incompatibility issue?

### ISSUE THREAD

**Issue by olhapi** [supertokens/supertokens-node#233]
![image](https://user-images.githubusercontent.com/4780263/146033724-cf805184-c034-49fa-8b3e-50d8a66f8042.png)

Trying to add supertokens-node to my nestjs server. 

Module setup from this guide (https://supertokens.io/docs/thirdpartyemailpassword/nestjs/guide) is somewhat finished (although there are a few mistakes in it, is there a repo with website where I can fix them?) but then I've got this error (see screenshot). I haven't installed any supertokens core thing and have no idea how to install it.

**Comment by rishabhpoddar** [comment]
>  is there a repo with website where I can fix them?

Yes. You can issue a PR for this repo: https://github.com/supertokens/docs (you should find the right file to edit by clicking on the edit button at the bottom of the page

> I haven't installed any supertokens core thing and have no idea how to install it.

The backend APIs exposed our backend SDK relies on talking to the "supertokens core" service (See [architecture page](https://supertokens.io/docs/community/architecture)). If you use `https://try.supertokens.io` as the `connectionURI` in the supertokens.init function, then you are using a core hosted by us for trial purposes. (which should be compatible with `^8.2.1` of node SDK). If instead, you are using our managed service, and have supplied a connectionURI and an apiKey in the config as shown on our dashboard, then you must use the version of the node SDK that is compatible with the version of the core. You can find the compatibility table here: https://supertokens.io/docs/community/compatibility-table. If instead, you would like to update the version of the core that is deployed by us, then please let me know, and we will update it to the latest version (which should work with ^8.2.1)

I am closing this issue for now since it's not an actual issue with our code. But feel free to reopen it :)
