### ISSUE TITLE
Email shouldn't be optional in the return type of getProfileInfo

### ISSUE THREAD

**Issue by giorgosera** [supertokens/supertokens-node#380]
According to the type [here](https://github.com/supertokens/supertokens-node/blob/5a00a138/lib/ts/recipe/thirdparty/types.ts#L32) the email object is optional. 

After a conversation with @rishabhpoddar on Discord he asked to open this issue as this shouldn't be the case. 
Also the guide [here](https://supertokens.com/docs/thirdparty/common-customizations/sign-in-and-up/custom-providers) has a comment in the code that says that email is optional so this might need to change too.

**Comment by rishabhpoddar** [comment]
Hey! On second thought, from a types point of view, email should be optional since that displays to the user to chose another method of of login. The alternative would be to return a fake email with `isVerified` as `true` and things would continue to work as is. The first option is generally better when multiple forms of login are available, hence the type should remain as optional IMO.
